In [1]:
#importing numpy
import numpy as np 

In [5]:
#Checking the version

np.__version__


'1.21.5'

In [4]:
#Using nd-array

nparray = np.array([1,2,3,4,5])
nparray

array([1, 2, 3, 4, 5])

In [5]:
#datatype of array 

nparray.dtype

dtype('int32')

In [10]:
#Size of the array
nparray.size

5

In [11]:
#Shape of an array 

nparray.shape

(5,)

In [6]:
#Comparing numpy array with python's list

%timeit pythonList = [i for i in range(10000)]

%timeit npList = np.arange(10000)

281 µs ± 1.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
5.49 µs ± 19.8 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [13]:
#Generating data with numpy

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
#Create an array of 1 
np.ones(5)

array([1., 1., 1., 1., 1.])

In [16]:
#Creating an array of 0
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
#eye creates an identity matrix.
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
#empty creates an array filled with garbage values
np.empty(5)

array([1., 1., 1., 1., 1.])

In [7]:
#Indexing

arr=np.array([32,23,31,44,55,66])
arr[1]

23

In [8]:
arr[-1]

66

In [9]:
#Slicing

arr[0:3]

array([32, 23, 31])

In [10]:
arr[3:4]

array([44])

In [11]:
arr[:]

array([32, 23, 31, 44, 55, 66])

In [54]:
arr[-3:]

array([44, 55, 66])

In [55]:
#Axes
np.arange(1, 7).reshape((2, 3))

array([[1, 2, 3],
       [4, 5, 6]])

In [56]:
np.arange(1, 4)

array([1, 2, 3])

In [58]:
np.arange(1, 4).reshape(1,3)

array([[1, 2, 3]])

In [60]:
#Array Concatenation
smallArray=np.array([1,2,3,4,5])
largeArray=np.array([5,3,2,5,2])
np.concatenate([smallArray, largeArray])

array([1, 2, 3, 4, 5, 5, 3, 2, 5, 2])

In [61]:
#numpy Ufuncs
#primary purpose of Ufunc is to be able to speed up repeated operations on values in a numpy array.
3 * np.arange(0, 10)

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [62]:
np.arange(0, 10) + np.arange(20, 30)

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38])

In [66]:
#Its also faster. Lets try that out below
%timeit 3 * smallArray

863 ns ± 139 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [67]:
#Aggregation

np.sum(smallArray)

15

In [68]:
np.min(smallArray)

1

In [69]:
np.max(smallArray)

5

In [70]:
np.std(smallArray)

1.4142135623730951

In [71]:
np.mean(smallArray)

3.0

In [73]:
np.median(smallArray)

3.0

In [74]:
np.nanmean(np.array([1, 2, np.nan]))

1.5

In [75]:
np.mean(np.array([1, 2, np.nan]))

nan

In [77]:
#Broadcasting
a = np.arange(1, 7)
a

array([1, 2, 3, 4, 5, 6])

In [78]:
a + 1

array([2, 3, 4, 5, 6, 7])

In [79]:
#Logical Operations
x = np.array([1, 2, 3, 4])
x>2

array([False, False,  True,  True])

In [80]:
x = np.array([1, 2, 3, 4])
x==2

array([False,  True, False, False])

In [81]:
np.any(x == 2)

True

In [82]:
np.all(x == 2)

False

In [84]:
#Masking
x[x == 2]

array([2])

In [85]:
x[x > 2]

array([3, 4])

In [86]:
#Multiple access indexing
x[[0, 2, 3]]


array([1, 3, 4])

In [87]:
#Sorting

np.random.shuffle(x)
x

array([1, 4, 3, 2])

In [88]:
np.sort(x)

array([1, 2, 3, 4])